version: '2'

services:
  hiring-fullstack-javascript-exercise:
    image: hiring-fullstack-javascript-exercise
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:4000
    volumes:
      - "./:/src"
    environment:
      - PORT=3000
